### ISSUE TITLE
Bug Headers aparecendo dentro da tabela

### ISSUE THREAD

**Issue by ArthurFerreiraRodrigues** [fga-eps-mds/Speak-Up#85]
## Descrição
Devido a um erro no markdown, os headers estão aparecendo dentro da tabela de backlog.

## Etapas para Reproduzir o Problema

1. Acessar https://fga-eps-mds.github.io/2023.1-GuiaUnB/Pages/backlog/2023-05-06-backlog/

## Comportamento Atual
Headers aparecendo dentro da tabela.
![image](https://github.com/fga-eps-mds/2023.1-GuiaUnB/assets/69909375/3e26f7a5-a704-4418-9cfc-86d6446b8b13)

**Comment by ArthurFerreiraRodrigues** [comment]
Vim pelo LinkedIn. Parabéns pelo projeto!

**Comment by ArthurGabrieel** [comment]
Obrigado por avisar, amigo!
